name: CD

on:
  push:
    branches:
      - main

jobs:
  cd:
    strategy:
      matrix:
        os:
          - "ubuntu-latest"

        python-version:
          - "3.10"

    concurrency: cd
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pip Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config installer.parallel true --local
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - name: Poetry Cache
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        run: |
          poetry install

      - name: Run Formatting Task
        run: |
          poetry run task format

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          git_committer_name: "Obscurity Labs Bot"
          git_committer_email: "github@obscuritylabs.com"
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - name: Run Release Task
        run: |
          poetry run task release
        env:
          REPOSITORY_USERNAME: __token__
          REPOSITORY_PASSWORD: ${{ secrets.PYPI_TOKEN }}
